apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mudassir-dev0ps/argo.git
    targetRevision: master
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
